[serviceweaver]
binary = "./workshops"

["github.com/ServiceWeaver/workshops/ChatGPT"]
# Paste your OpenAI API key here. You can generate an API key at
# https://platform.openai.com/account/api-keys. Be careful not to push your API
# key to GitHub.
api_key = ""
